# Generated by Django 5.0.1 on 2024-03-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
